apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
name: ecom-hpa
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: ecom-backend
minReplicas: 2
maxReplicas: 5
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 50