apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: ecom-backend-sm
labels:
release: prom
spec:
selector:
matchLabels:
app: ecom-backend
endpoints:
- port: http
path: /metrics
interval: 15s